In [4]:
from models import AutoRegression, PowerSlope

import pandas as pd
from dbm import DBM

### Load Data

In [5]:
db = DBM(user='kenny.liao')

In [6]:
# pull most recent
# ke_data = db.get_market_data(market='ke', days_before=0)
# ph_data = db.get_market_data(market='ph', days_before=0)
mx_data = db.get_market_data(market='mx', days_before=0)

### Generate Model

In [7]:
# generate models
# ke = AutoRegression(ke_data, market='ke')
# ph = AutoRegression(ph_data, market='ph')
mx = AutoRegression(mx_data, market='mx')

Clean data spans 2020-09 to 2022-02
Total # of cohorts: 18

### Generate Forecasts

In [8]:
mx.forecast = mx.forecast_data(mx.data, min_months=1, n_months=50)

### Prepare Data for Upload

In [ ]:
df = mx.forecast.copy()

# change first loan disbursement month to datetime
df['First Loan Local Disbursement Month'] = pd.to_datetime(df['First Loan Local Disbursement Month']).dt.date

### Load data

In [13]:
mx.forecast.to_sql(name='ltv_mx', con=db.engine.connect(), schema='FINANCE_MX', if_exists='replace', index=False)

### Query to Check Data

In [14]:
sql = """
SELECT * FROM ltv_mx
"""

In [15]:
mx_check = pd.read_sql_query(sql, db.engine)

In [16]:
mx_check

,First_Loan_Local_Disbursement_Month,Months_Since_First_Loan_Disbursed,Count_First_Loans,Count_Borrowers,Count_Loans,Total_Amount,Total_Interest_Assessed,Total_Rollover_Charged,Total_Rollover_Reversed,Default_Rate_Amount_7D,...,opex_coc_per_original,cumulative_opex_coc_per_original,opex_cpl_per_original,cumulative_opex_cpl_per_original,ltv_per_original,cumulative_ltv_per_original,dcf_ltv_per_original,cumulative_dcf_ltv_per_original,crm_perc_per_original,data_type
0,2020-09-01,0,22353.0,22353,43447,1668235,324482.50,22884.85,125.2,0.113774,...,0.808507,0.808507,2.662837,2.662837,2.814414,2.814414,2.779668,2.779668,0.183616,actual
1,2020-09-01,1,0.0,15462,20496,1319490,254866.70,20096.50,118.9,0.126074,...,0.639488,1.447994,1.256186,3.919023,2.266215,5.080629,2.210942,4.990610,0.187101,actual
2,2020-09-01,2,0.0,12378,15218,1171135,227001.40,19068.30,129.0,0.131780,...,0.567588,2.015583,0.932701,4.851723,2.084813,7.165442,2.009458,7.000068,0.192776,actual
3,2020-09-01,3,0.0,10471,12632,1100040,214758.80,17932.65,304.1,0.131947,...,0.533132,2.548715,0.774207,5.625930,2.211536,9.376978,2.106224,9.106293,0.216213,actual
4,2020-09-01,4,0.0,9208,11187,1091930,212117.05,17053.00,172.1,0.123553,...,0.529202,3.077916,0.685644,6.311573,2.615190,11.992168,2.461355,11.567648,0.259803,actual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,2022-02-01,45,NaN,418,497,98661,NaN,NaN,NaN,NaN,...,0.050013,10.247152,0.031860,11.471498,0.510897,68.402965,0.324379,55.089247,0.577563,forecast
896,2022-02-01,46,NaN,393,467,92706,NaN,NaN,NaN,NaN,...,0.046994,10.294146,0.029937,11.501436,0.480058,68.883023,0.302399,55.391646,0.577563,forecast
897,2022-02-01,47,NaN,369,439,87147,NaN,NaN,NaN,NaN,...,0.044177,10.338323,0.028142,11.529578,0.451275,69.334298,0.282047,55.673693,0.577563,forecast
898,2022-02-01,48,NaN,347,412,81788,NaN,NaN,NaN,NaN,...,0.041460,10.379783,0.026411,11.555989,0.423520,69.757818,0.262648,55.936341,0.577563,forecast
899,2022-02-01,49,NaN,326,387,76825,NaN,NaN,NaN,NaN,...,0.038944,10.418727,0.024809,11.580798,0.397821,70.155640,0.244813,56.181154,0.577563,forecast